### ISSUE TITLE
Centos node 17 build error, should add node v17 

### ISSUE THREAD

**Issue by tianyingchun** [Brouilles/bsdiff-node#23]
npm i  bsdiff-node --registry=https://registry.npmjs.org/

npm ERR! code 1
npm ERR! path /opt/applications/team/venus-doc/node_modules/bsdiff-node
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory `/opt/applications/team/venus-doc/node_modules/bsdiff-node/build'
npm ERR!   CXX(target) Release/obj.target/bsdiff/src/Main.o
npm ERR! make: Leaving directory `/opt/applications/team/venus-doc/node_modules/bsdiff-node/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@17.9.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/bin/python3"
npm ERR! gyp info spawn /bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/applications/team/venus-doc/node_modules/bsdiff-node/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/17.9.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/17.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/17.9.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/applications/team/venus-doc/node_modules/bsdiff-node',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++17’
npm ERR! make: *** [Release/obj.target/bsdiff/src/Main.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-957.el7.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /opt/applications/team/venus-doc/node_modules/bsdiff-node
npm ERR! gyp ERR! node -v v17.9.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

**Comment by Brouilles** [comment]
Doesn't seems related to NodeJS 17. But to the C compiler. Maybe too old.
What version do you have of CentOS? What version of gcc?

Run:
`gcc --version`
`g++ --version`

**Comment by tianyingchun** [comment]
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

CentOS Linux release 7.6.1810 (Core) 

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by tianyingchun** [comment]
Just upgrade gcc, g++, install successfully
```shell
1. yum -y install centos-release-scl
2. yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-binutils
3. scl enable devtoolset-8 bash #startup gcc8 session
4. npm i bsdiff-node
```
it works
