### ISSUE TITLE
Can't build the module

### ISSUE THREAD

**Issue by NoFrosty** [Brouilles/bsdiff-node#24]
Hello,

When trying to use this module, I got an error for nodejs version: 
`Error: The module '\\?\C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\Release\bsdiff.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 107. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).`

When trying to npm rebuild, run again, same error.

I tried to install electron-rebuild, and rebuild from this module, but got : 
`
Building module: bsdiff-node, Completed: 0C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan_callbacks.h(55,23): error C2039: 'AccessorSignature' n'est pas membre de 'v8' [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\.electron-gyp\20.1.3\include\node\v8.h(71): message : voir la déclaration de 'v8' [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan_callbacks.h(55,40): error C2065: 'AccessorSignature' : identificateur non déclaré [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan_callbacks.h(55,13): error C2923: 'v8::Local' : 'AccessorSignature' n'est pas un argument de type modèle valide pour le paramètre 'T' [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_ 
modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan.h(2520,36): error C2512: 'v8::Local' : aucun constructeur par défaut approprié disponible [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan.h(2520,36): message : Aucun constructeur n'a pu prendre le type de source, ou la résolution de la surcharge du constructeur était ambiguë [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\ 
node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan.h(2546,6): error C2664: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::Property 
Attribute,v8::SideEffectType,v8::SideEffectType)' : impossible de convertir l'argument 2 de 'Nan::imp::NativeGetter' en 'v8::AccessorGetterCallback' [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\nan\nan.h(2548,7): message : Cette conversion requiert reinterpret_cast, un cast de style C ou un cast de style fonction [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\ 
build\bsdiff.vcxproj]
C:\Users\Calvi\.electron-gyp\20.1.3\include\node\v8-template.h(807,8): message : voir la déclaration de 'v8::ObjectTemplate::SetAccessor' [C:\Users\Calvi\Documents\GitHub\electron-vite-vue\node_modules\bsdiff-node\build\bsdiff.vcxproj]
✖ Rebuild Failed`

This is in french sorry but mostly the errors are: There is no Constructor | XXX is not a valid template type argument for parameter...

![image](https://user-images.githubusercontent.com/9253013/189523989-7fb9ad1d-9bdc-4f2a-bf50-976d70f347f7.png)

node: 16.17.0
npm: 8.19.1
python: 3.10.0
Visual Studio: 2019 with desktop development C++ workload

**Comment by Brouilles** [comment]
Maybe try 
```
npm rebuild bsdiff-node --update-binary
```

**Comment by NoFrosty** [comment]
I already tried this unsuccessfully. (npm rebuilt it but still got the same Module Version error)

You can find a minimalist version of me project here:
https://github.com/NoFrosty/template-errorbsdiff

This is just the template I use + bsdiff that's all.

**Comment by Brouilles** [comment]
The problem is not on `bsdiff-node`. Who compile well with NodeJS `v16.17.0`.
You can try to copy the repo and run `npm run install` and `npm run test` to verify that. I can't help you more for a use with Electron. It is out of the scope of this repository.
